
CXX		= g++
LD              = g++
LDFLAGS         += -Wl,-rpath,$(NEMLIBDIR)/lib 
FFLAGS          += -Wall -std=c++11
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g  -Wall  -D_NEM_$(shell uname -s)_ #-std=c++11
SOMAKER         = g++
SOFLAGS         = -g -shared 
