#ifndef __MCTrack_H__
#define __MCTrack_H__

/**
 * @file MCTrack.h
 *
 * @class MCTrack
 * 
 * @brief Class for true track objects
 *
 * @details Contains a collection of true hits generated by a true particle
 *    
 * @author Pau Novella  <pau.novella@ific.uv.es>
 *
 * @version Revision 1.0.0
 *
 * @date January 2015
 *
 */

#include <iostream>

#include<TSystem.h>

#include<BTrack.h>
#include<MCParticle.h>

namespace gate{class MCTrack;}

class gate::MCTrack : public gate::BTrack {

 public:
 
  //! default constructor
  MCTrack();
  
  //! destructor
  virtual ~MCTrack(){} 
  
  //! retrieve particle generating the track
  const gate::MCParticle& GetMCParticle() const;

  //! set particle generating the track
  void SetMCParticle(gate::MCParticle* p);
   
  //! print event into stream
  void Info(ostream& s) const;

 protected:
  
  //! true particle responsible for the track
  const  gate::MCParticle* _part;

  ClassDef(gate::MCTrack,1)

};

inline const gate::MCParticle& gate::MCTrack::GetMCParticle() const 
{return *_part;}

inline void gate::MCTrack::SetMCParticle(gate::MCParticle* p)  { _part = p;}

ostream& operator << (ostream& s, const gate::MCTrack& trk) ;

#endif
