/********************************************************************
* GATEIOCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GATEIOCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGATEIOCint();
extern void G__cpp_setup_inheritanceGATEIOCint();
extern void G__cpp_setup_typetableGATEIOCint();
extern void G__cpp_setup_memvarGATEIOCint();
extern void G__cpp_setup_globalGATEIOCint();
extern void G__cpp_setup_memfuncGATEIOCint();
extern void G__cpp_setup_funcGATEIOCint();
extern void G__set_cpp_environmentGATEIOCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IReader.h"
#include "IWriter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GATEIOCintLN_TClass;
extern G__linked_taginfo G__GATEIOCintLN_TBuffer;
extern G__linked_taginfo G__GATEIOCintLN_TMemberInspector;
extern G__linked_taginfo G__GATEIOCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__GATEIOCintLN_string;
extern G__linked_taginfo G__GATEIOCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GATEIOCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEIOCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GATEIOCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEIOCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__GATEIOCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEIOCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GATEIOCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GATEIOCintLN_gate;
extern G__linked_taginfo G__GATEIOCintLN_gatecLcLEvent;
extern G__linked_taginfo G__GATEIOCintLN_gatecLcLIReader;
extern G__linked_taginfo G__GATEIOCintLN_gatecLcLIWriter;

/* STUB derived class for protected member access */
