/********************************************************************
* GATECint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GATECint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGATECint();
extern void G__cpp_setup_inheritanceGATECint();
extern void G__cpp_setup_typetableGATECint();
extern void G__cpp_setup_memvarGATECint();
extern void G__cpp_setup_globalGATECint();
extern void G__cpp_setup_memfuncGATECint();
extern void G__cpp_setup_funcGATECint();
extern void G__set_cpp_environmentGATECint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IReader.h"
#include "IWriter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GATECintLN_TClass;
extern G__linked_taginfo G__GATECintLN_TBuffer;
extern G__linked_taginfo G__GATECintLN_TMemberInspector;
extern G__linked_taginfo G__GATECintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__GATECintLN_string;
extern G__linked_taginfo G__GATECintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GATECintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATECintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GATECintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATECintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__GATECintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATECintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GATECintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GATECintLN_gate;
extern G__linked_taginfo G__GATECintLN_gatecLcLEvent;
extern G__linked_taginfo G__GATECintLN_gatecLcLIReader;
extern G__linked_taginfo G__GATECintLN_gatecLcLIWriter;

/* STUB derived class for protected member access */
