/********************************************************************
* GATEUtilCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GATEUtilCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGATEUtilCint();
extern void G__cpp_setup_inheritanceGATEUtilCint();
extern void G__cpp_setup_typetableGATEUtilCint();
extern void G__cpp_setup_memvarGATEUtilCint();
extern void G__cpp_setup_globalGATEUtilCint();
extern void G__cpp_setup_memfuncGATEUtilCint();
extern void G__cpp_setup_funcGATEUtilCint();
extern void G__set_cpp_environmentGATEUtilCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ParamStore.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GATEUtilCintLN_TClass;
extern G__linked_taginfo G__GATEUtilCintLN_TBuffer;
extern G__linked_taginfo G__GATEUtilCintLN_TMemberInspector;
extern G__linked_taginfo G__GATEUtilCintLN_TObject;
extern G__linked_taginfo G__GATEUtilCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_string;
extern G__linked_taginfo G__GATEUtilCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEUtilCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEUtilCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEUtilCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEUtilCintLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEUtilCintLN_vectorlETObjectmUcOallocatorlETObjectmUgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_reverse_iteratorlEvectorlETObjectmUcOallocatorlETObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GATEUtilCintLN_gate;
extern G__linked_taginfo G__GATEUtilCintLN_gatecLcLParamStore;
extern G__linked_taginfo G__GATEUtilCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_maplEstringcOTObjectmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjectmUgRsPgRsPgR;
extern G__linked_taginfo G__GATEUtilCintLN_maplEstringcOvectorlETObjectmUcOallocatorlETObjectmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETObjectmUcOallocatorlETObjectmUgRsPgRsPgRsPgRsPgR;

/* STUB derived class for protected member access */
